name: Push Source to Dev Repo (Safe Version)

on:
  push:
    branches:
      - main

jobs:
  sync-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Setup Git Config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone Dev Repo (Shallow)
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # 克隆 dev 仓库（仅 main 分支）
          git clone --depth=1 https://${GH_TOKEN}@github.com/yichixing/hugo-stack-AllPlatformVersiond-dev.git dev-repo

      - name: Copy Source Files (Exclude Sensitive Files)
        run: |
          # 安全复制源码（排除敏感文件）
          rsync -a \
            --exclude='public/' \
            --exclude='.git/' \
            --exclude='themes/FixIt/assets/lib/twikoo/twikoo.all.min.js' \
            ./ dev-repo/

      - name: Commit and Push Changes
        working-directory: dev-repo
        run: |
          # 检查是否有变更
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Sync source from main repo [skip ci]"
            git push origin main
          fi
